// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAPIKey(arg1, arg2, arg3) {
  return window['go']['main']['APIService']['CreateAPIKey'](arg1, arg2, arg3);
}

export function GetAPIStatus() {
  return window['go']['main']['APIService']['GetAPIStatus']();
}

export function ListAPIKeys() {
  return window['go']['main']['APIService']['ListAPIKeys']();
}

export function RevokeAPIKey(arg1) {
  return window['go']['main']['APIService']['RevokeAPIKey'](arg1);
}

export function StartAPI(arg1, arg2) {
  return window['go']['main']['APIService']['StartAPI'](arg1, arg2);
}

export function StopAPI() {
  return window['go']['main']['APIService']['StopAPI']();
}
