// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateAPIKey(arg1:string,arg2:string,arg3:number):Promise<main.APIKeyCreateResult>;

export function GetAPIStatus():Promise<main.APIStatus>;

export function ListAPIKeys():Promise<Array<main.APIKeyInfo>>;

export function RevokeAPIKey(arg1:number):Promise<void>;

export function StartAPI(arg1:number,arg2:boolean):Promise<main.APIStatus>;

export function StopAPI():Promise<void>;
