// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BulkArchive(arg1) {
  return window['go']['main']['App']['BulkArchive'](arg1);
}

export function BulkDelete(arg1) {
  return window['go']['main']['App']['BulkDelete'](arg1);
}

export function BulkDownloadToFile(arg1) {
  return window['go']['main']['App']['BulkDownloadToFile'](arg1);
}

export function CancelExpiration(arg1) {
  return window['go']['main']['App']['CancelExpiration'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateTempFile(arg1) {
  return window['go']['main']['App']['CreateTempFile'](arg1);
}

export function DeleteAllTempFiles() {
  return window['go']['main']['App']['DeleteAllTempFiles']();
}

export function DeleteClip(arg1) {
  return window['go']['main']['App']['DeleteClip'](arg1);
}

export function GetClipData(arg1) {
  return window['go']['main']['App']['GetClipData'](arg1);
}

export function GetClipboardImage() {
  return window['go']['main']['App']['GetClipboardImage']();
}

export function GetClipboardText() {
  return window['go']['main']['App']['GetClipboardText']();
}

export function GetClips(arg1) {
  return window['go']['main']['App']['GetClips'](arg1);
}

export function ReadFileFromPath(arg1) {
  return window['go']['main']['App']['ReadFileFromPath'](arg1);
}

export function SaveClipToFile(arg1) {
  return window['go']['main']['App']['SaveClipToFile'](arg1);
}

export function ToggleArchive(arg1) {
  return window['go']['main']['App']['ToggleArchive'](arg1);
}

export function UploadFiles(arg1, arg2) {
  return window['go']['main']['App']['UploadFiles'](arg1, arg2);
}
