// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWatchedFolder(arg1) {
  return window['go']['main']['App']['AddWatchedFolder'](arg1);
}

export function BulkArchive(arg1) {
  return window['go']['main']['App']['BulkArchive'](arg1);
}

export function BulkDelete(arg1) {
  return window['go']['main']['App']['BulkDelete'](arg1);
}

export function BulkDownloadToFile(arg1) {
  return window['go']['main']['App']['BulkDownloadToFile'](arg1);
}

export function CancelExpiration(arg1) {
  return window['go']['main']['App']['CancelExpiration'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateTempFile(arg1) {
  return window['go']['main']['App']['CreateTempFile'](arg1);
}

export function DeleteAllTempFiles() {
  return window['go']['main']['App']['DeleteAllTempFiles']();
}

export function DeleteClip(arg1) {
  return window['go']['main']['App']['DeleteClip'](arg1);
}

export function GetClipData(arg1) {
  return window['go']['main']['App']['GetClipData'](arg1);
}

export function GetClipboardImage() {
  return window['go']['main']['App']['GetClipboardImage']();
}

export function GetClipboardText() {
  return window['go']['main']['App']['GetClipboardText']();
}

export function GetClips(arg1) {
  return window['go']['main']['App']['GetClips'](arg1);
}

export function GetGlobalWatchPaused() {
  return window['go']['main']['App']['GetGlobalWatchPaused']();
}

export function GetWatchStatus() {
  return window['go']['main']['App']['GetWatchStatus']();
}

export function GetWatchedFolders() {
  return window['go']['main']['App']['GetWatchedFolders']();
}

export function ProcessExistingFilesInFolder(arg1) {
  return window['go']['main']['App']['ProcessExistingFilesInFolder'](arg1);
}

export function ReadFileFromPath(arg1) {
  return window['go']['main']['App']['ReadFileFromPath'](arg1);
}

export function RefreshWatches() {
  return window['go']['main']['App']['RefreshWatches']();
}

export function RemoveWatchedFolder(arg1) {
  return window['go']['main']['App']['RemoveWatchedFolder'](arg1);
}

export function SaveClipToFile(arg1) {
  return window['go']['main']['App']['SaveClipToFile'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetFolderPaused(arg1, arg2) {
  return window['go']['main']['App']['SetFolderPaused'](arg1, arg2);
}

export function SetGlobalWatchPaused(arg1) {
  return window['go']['main']['App']['SetGlobalWatchPaused'](arg1);
}

export function ToggleArchive(arg1) {
  return window['go']['main']['App']['ToggleArchive'](arg1);
}

export function UpdateWatchedFolder(arg1, arg2) {
  return window['go']['main']['App']['UpdateWatchedFolder'](arg1, arg2);
}

export function UploadFiles(arg1, arg2) {
  return window['go']['main']['App']['UploadFiles'](arg1, arg2);
}
