// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTagToClip(arg1:number,arg2:number):Promise<void>;

export function AddWatchedFolder(arg1:main.WatchedFolderConfig):Promise<main.WatchedFolder>;

export function BulkAddTag(arg1:Array<number>,arg2:number):Promise<void>;

export function BulkArchive(arg1:Array<number>):Promise<void>;

export function BulkCancelExpiration(arg1:Array<number>):Promise<void>;

export function BulkDelete(arg1:Array<number>):Promise<void>;

export function BulkDownloadToFile(arg1:Array<number>):Promise<void>;

export function BulkRemoveTag(arg1:Array<number>,arg2:number):Promise<void>;

export function BulkSetExpiration(arg1:Array<number>,arg2:number):Promise<void>;

export function CancelExpiration(arg1:number):Promise<void>;

export function ConfirmRestoreBackup(arg1:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateBackup(arg1:string):Promise<void>;

export function CreateTag(arg1:string):Promise<main.Tag>;

export function CreateTempFile(arg1:number):Promise<string>;

export function DeduplicateAll():Promise<number>;

export function DeleteAllTempFiles():Promise<void>;

export function DeleteClip(arg1:number):Promise<void>;

export function DeleteClipMetadata(arg1:number,arg2:string):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function GetClipData(arg1:number):Promise<main.ClipData>;

export function GetClipMetadata(arg1:number):Promise<Record<string, string>>;

export function GetClipTags(arg1:number):Promise<Array<main.Tag>>;

export function GetClipboardImage():Promise<string>;

export function GetClipboardText():Promise<string>;

export function GetClips(arg1:boolean,arg2:Array<number>,arg3:Array<number>,arg4:string,arg5:string):Promise<Array<main.ClipPreview>>;

export function GetDuplicateGroups():Promise<Array<main.DuplicateGroup>>;

export function GetGlobalWatchPaused():Promise<boolean>;

export function GetHiddenTags():Promise<Array<number>>;

export function GetImageDiff(arg1:number,arg2:number,arg3:number):Promise<main.DiffResult>;

export function GetSetting(arg1:string):Promise<string>;

export function GetTags():Promise<Array<main.Tag>>;

export function GetWatchStatus():Promise<main.WatchStatus>;

export function GetWatchedFolderByID(arg1:number):Promise<main.WatchedFolder>;

export function GetWatchedFolders():Promise<Array<main.WatchedFolder>>;

export function IsDirectory(arg1:string):Promise<boolean>;

export function MergeDuplicates(arg1:number):Promise<void>;

export function ProcessExistingFilesInFolder(arg1:number):Promise<void>;

export function ReadFileFromPath(arg1:string):Promise<main.FileData>;

export function RefreshWatches():Promise<void>;

export function RemoveTagFromClip(arg1:number,arg2:number):Promise<void>;

export function RemoveWatchedFolder(arg1:number):Promise<void>;

export function RestoreBackup(arg1:string):Promise<void>;

export function SaveClipToFile(arg1:number):Promise<void>;

export function SelectFolder():Promise<string>;

export function SetClipMetadata(arg1:number,arg2:string,arg3:string):Promise<void>;

export function SetClipMetadataBulk(arg1:number,arg2:Record<string, string>):Promise<void>;

export function SetExpiration(arg1:number,arg2:number):Promise<void>;

export function SetFolderPaused(arg1:number,arg2:boolean):Promise<void>;

export function SetGlobalWatchPaused(arg1:boolean):Promise<void>;

export function SetHiddenTags(arg1:Array<number>):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function ShowCreateBackupDialog():Promise<string>;

export function ShowRestoreBackupDialog():Promise<main.BackupManifest>;

export function ToggleArchive(arg1:number):Promise<void>;

export function UpdateTag(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateWatchedFolder(arg1:number,arg2:main.WatchedFolderConfig):Promise<void>;

export function UploadFileAndGetID(arg1:main.FileData):Promise<number>;

export function UploadFiles(arg1:Array<main.FileData>,arg2:number):Promise<void>;
