// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BulkCopyFilesToClipboard(arg1) {
  return window['go']['main']['ClipboardService']['BulkCopyFilesToClipboard'](arg1);
}

export function CopyClipContents(arg1) {
  return window['go']['main']['ClipboardService']['CopyClipContents'](arg1);
}

export function CopyFileToClipboard(arg1) {
  return window['go']['main']['ClipboardService']['CopyFileToClipboard'](arg1);
}
