// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BulkCopyFilesToClipboard(arg1:Array<number>):Promise<void>;

export function CopyClipContents(arg1:number):Promise<void>;

export function CopyFileToClipboard(arg1:number):Promise<void>;
