// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Disable():Promise<main.FileProviderStatus>;

export function Enable():Promise<main.FileProviderStatus>;

export function Reveal():Promise<void>;

export function Status():Promise<main.FileProviderStatus>;
