// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Disable() {
  return window['go']['main']['FileProviderService']['Disable']();
}

export function Enable() {
  return window['go']['main']['FileProviderService']['Enable']();
}

export function Reveal() {
  return window['go']['main']['FileProviderService']['Reveal']();
}

export function Status() {
  return window['go']['main']['FileProviderService']['Status']();
}
