// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateShareLink(arg1, arg2, arg3, arg4) {
  return window['go']['main']['LinkService']['CreateShareLink'](arg1, arg2, arg3, arg4);
}

export function ListShareLinks() {
  return window['go']['main']['LinkService']['ListShareLinks']();
}

export function RevokeShareLink(arg1) {
  return window['go']['main']['LinkService']['RevokeShareLink'](arg1);
}
