// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CreateShareLink(arg1:number,arg2:string,arg3:number,arg4:number):Promise<app.ShareLinkCreateResult>;

export function ListShareLinks():Promise<Array<app.ShareLinkInfo>>;

export function RevokeShareLink(arg1:number):Promise<void>;
