// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CancelRemoteImage(arg1:string):Promise<boolean>;

export function ClearImageCache():Promise<void>;

export function GetCachedRemoteImage(arg1:string):Promise<app.MarkdownCachedImageResult>;

export function GetImageCacheStats():Promise<app.MarkdownImageCacheStats>;

export function GetLocalImage(arg1:number):Promise<app.MarkdownImageData>;

export function LoadRemoteImage(arg1:string,arg2:string):Promise<app.MarkdownRemoteImageResult>;

export function ResolveReferences(arg1:number,arg2:Array<string>):Promise<Array<app.MarkdownReferenceResult>>;

export function ValidateEmbeddedImage(arg1:string,arg2:string):Promise<app.MarkdownImageData>;
