// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRemoteImage(arg1) {
  return window['go']['main']['MarkdownService']['CancelRemoteImage'](arg1);
}

export function ClearImageCache() {
  return window['go']['main']['MarkdownService']['ClearImageCache']();
}

export function GetCachedRemoteImage(arg1) {
  return window['go']['main']['MarkdownService']['GetCachedRemoteImage'](arg1);
}

export function GetImageCacheStats() {
  return window['go']['main']['MarkdownService']['GetImageCacheStats']();
}

export function GetLocalImage(arg1) {
  return window['go']['main']['MarkdownService']['GetLocalImage'](arg1);
}

export function LoadRemoteImage(arg1, arg2) {
  return window['go']['main']['MarkdownService']['LoadRemoteImage'](arg1, arg2);
}

export function ResolveReferences(arg1, arg2) {
  return window['go']['main']['MarkdownService']['ResolveReferences'](arg1, arg2);
}

export function ValidateEmbeddedImage(arg1, arg2) {
  return window['go']['main']['MarkdownService']['ValidateEmbeddedImage'](arg1, arg2);
}
