// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisablePlugin(arg1) {
  return window['go']['main']['PluginService']['DisablePlugin'](arg1);
}

export function EnablePlugin(arg1) {
  return window['go']['main']['PluginService']['EnablePlugin'](arg1);
}

export function GetPluginPermissions(arg1) {
  return window['go']['main']['PluginService']['GetPluginPermissions'](arg1);
}

export function GetPlugins() {
  return window['go']['main']['PluginService']['GetPlugins']();
}

export function ImportPlugin() {
  return window['go']['main']['PluginService']['ImportPlugin']();
}

export function RemovePlugin(arg1) {
  return window['go']['main']['PluginService']['RemovePlugin'](arg1);
}

export function RevokePluginPermission(arg1, arg2, arg3) {
  return window['go']['main']['PluginService']['RevokePluginPermission'](arg1, arg2, arg3);
}
