// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DisablePlugin(arg1:number):Promise<void>;

export function EnablePlugin(arg1:number):Promise<void>;

export function GetAllPluginStorage(arg1:number):Promise<Record<string, string>>;

export function GetPluginPermissions(arg1:number):Promise<Array<Record<string, string>>>;

export function GetPluginStorage(arg1:number,arg2:string):Promise<string>;

export function GetPlugins():Promise<Array<main.PluginInfo>>;

export function ImportPlugin():Promise<main.PluginInfo>;

export function ImportPluginFromPath(arg1:string):Promise<main.PluginInfo>;

export function RemovePlugin(arg1:number):Promise<void>;

export function RevokePluginPermission(arg1:number,arg2:string,arg3:string):Promise<void>;

export function SetPluginStorage(arg1:number,arg2:string,arg3:string):Promise<void>;
