// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['PluginService']['CheckForUpdates']();
}

export function ConfirmPluginInstall(arg1) {
  return window['go']['main']['PluginService']['ConfirmPluginInstall'](arg1);
}

export function ConfirmPluginUpdate(arg1) {
  return window['go']['main']['PluginService']['ConfirmPluginUpdate'](arg1);
}

export function DisablePlugin(arg1) {
  return window['go']['main']['PluginService']['DisablePlugin'](arg1);
}

export function EnablePlugin(arg1) {
  return window['go']['main']['PluginService']['EnablePlugin'](arg1);
}

export function ExecutePluginAction(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['PluginService']['ExecutePluginAction'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAllPluginStorage(arg1) {
  return window['go']['main']['PluginService']['GetAllPluginStorage'](arg1);
}

export function GetPluginPermissions(arg1) {
  return window['go']['main']['PluginService']['GetPluginPermissions'](arg1);
}

export function GetPluginStorage(arg1, arg2) {
  return window['go']['main']['PluginService']['GetPluginStorage'](arg1, arg2);
}

export function GetPluginUIActions() {
  return window['go']['main']['PluginService']['GetPluginUIActions']();
}

export function GetPlugins() {
  return window['go']['main']['PluginService']['GetPlugins']();
}

export function GetUpdateCheckInterval() {
  return window['go']['main']['PluginService']['GetUpdateCheckInterval']();
}

export function ImportPlugin() {
  return window['go']['main']['PluginService']['ImportPlugin']();
}

export function ImportPluginFromPath(arg1) {
  return window['go']['main']['PluginService']['ImportPluginFromPath'](arg1);
}

export function IsPluginURLAllowed(arg1, arg2, arg3) {
  return window['go']['main']['PluginService']['IsPluginURLAllowed'](arg1, arg2, arg3);
}

export function PreviewPluginFromPath(arg1) {
  return window['go']['main']['PluginService']['PreviewPluginFromPath'](arg1);
}

export function PreviewPluginFromURL(arg1) {
  return window['go']['main']['PluginService']['PreviewPluginFromURL'](arg1);
}

export function RemovePlugin(arg1) {
  return window['go']['main']['PluginService']['RemovePlugin'](arg1);
}

export function RevokePluginPermission(arg1, arg2, arg3) {
  return window['go']['main']['PluginService']['RevokePluginPermission'](arg1, arg2, arg3);
}

export function SetPluginStorage(arg1, arg2, arg3) {
  return window['go']['main']['PluginService']['SetPluginStorage'](arg1, arg2, arg3);
}

export function SetUpdateCheckInterval(arg1) {
  return window['go']['main']['PluginService']['SetUpdateCheckInterval'](arg1);
}

export function TryAcquireModalGuard() {
  return window['go']['main']['PluginService']['TryAcquireModalGuard']();
}

export function UpdatePlugin(arg1) {
  return window['go']['main']['PluginService']['UpdatePlugin'](arg1);
}
