// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRandomPort() {
  return window['go']['main']['ServeService']['GetRandomPort']();
}

export function GetServeStatus() {
  return window['go']['main']['ServeService']['GetServeStatus']();
}

export function StartServing(arg1, arg2, arg3, arg4) {
  return window['go']['main']['ServeService']['StartServing'](arg1, arg2, arg3, arg4);
}

export function StopServing(arg1) {
  return window['go']['main']['ServeService']['StopServing'](arg1);
}
