// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetRandomPort():Promise<number>;

export function GetServeStatus():Promise<Array<main.ServeInfo>>;

export function StartServing(arg1:number,arg2:number,arg3:boolean):Promise<main.ServeInfo>;

export function StopServing(arg1:number):Promise<void>;
