// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {main} from '../models';

export function AgeShareRingForTest(arg1:number):Promise<void>;

export function DisconnectFollowForTest(arg1:number):Promise<void>;

export function Follow(arg1:string,arg2:string):Promise<app.FollowInfo>;

export function FollowWithoutDial(arg1:string,arg2:string):Promise<app.FollowInfo>;

export function GetShareLogs(arg1:number,arg2:number):Promise<Array<app.ShareLogEntry>>;

export function GetShareStatus():Promise<main.ShareStatus>;

export function PauseFollow(arg1:number):Promise<void>;

export function PauseShare(arg1:number):Promise<void>;

export function ReconnectFollow(arg1:number):Promise<void>;

export function ResumeFollow(arg1:number):Promise<void>;

export function ResumeShare(arg1:number):Promise<void>;

export function StartShare(arg1:number):Promise<app.ShareInfo>;

export function StopShare(arg1:number):Promise<void>;

export function TestFollowConnection(arg1:string):Promise<void>;

export function Unfollow(arg1:number):Promise<void>;

export function UpdateFollowTag(arg1:number,arg2:string):Promise<app.FollowInfo>;
