// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgeShareRingForTest(arg1) {
  return window['go']['main']['ShareService']['AgeShareRingForTest'](arg1);
}

export function DisconnectFollowForTest(arg1) {
  return window['go']['main']['ShareService']['DisconnectFollowForTest'](arg1);
}

export function Follow(arg1, arg2) {
  return window['go']['main']['ShareService']['Follow'](arg1, arg2);
}

export function FollowWithoutDial(arg1, arg2) {
  return window['go']['main']['ShareService']['FollowWithoutDial'](arg1, arg2);
}

export function GetShareLogs(arg1, arg2) {
  return window['go']['main']['ShareService']['GetShareLogs'](arg1, arg2);
}

export function GetShareStatus() {
  return window['go']['main']['ShareService']['GetShareStatus']();
}

export function PauseFollow(arg1) {
  return window['go']['main']['ShareService']['PauseFollow'](arg1);
}

export function PauseShare(arg1) {
  return window['go']['main']['ShareService']['PauseShare'](arg1);
}

export function ReconnectFollow(arg1) {
  return window['go']['main']['ShareService']['ReconnectFollow'](arg1);
}

export function ResumeFollow(arg1) {
  return window['go']['main']['ShareService']['ResumeFollow'](arg1);
}

export function ResumeShare(arg1) {
  return window['go']['main']['ShareService']['ResumeShare'](arg1);
}

export function StartShare(arg1) {
  return window['go']['main']['ShareService']['StartShare'](arg1);
}

export function StopShare(arg1) {
  return window['go']['main']['ShareService']['StopShare'](arg1);
}

export function TestFollowConnection(arg1) {
  return window['go']['main']['ShareService']['TestFollowConnection'](arg1);
}

export function Unfollow(arg1) {
  return window['go']['main']['ShareService']['Unfollow'](arg1);
}

export function UpdateFollowTag(arg1, arg2) {
  return window['go']['main']['ShareService']['UpdateFollowTag'](arg1, arg2);
}
