// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AgeShareRingForTest(arg1:number):Promise<void>;

export function DisconnectFollowForTest(arg1:number):Promise<void>;

export function Follow(arg1:string,arg2:string):Promise<main.FollowInfo>;

export function FollowWithoutDial(arg1:string,arg2:string):Promise<main.FollowInfo>;

export function GetShareStatus():Promise<main.ShareStatus>;

export function StartShare(arg1:number):Promise<main.ShareInfo>;

export function StopShare(arg1:number):Promise<void>;

export function TestFollowConnection(arg1:string):Promise<void>;

export function Unfollow(arg1:number):Promise<void>;

export function UpdateFollowTag(arg1:number,arg2:string):Promise<main.FollowInfo>;
