// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetExistingPreparedClipForTransfer(arg1) {
  return window['go']['main']['TransferService']['GetExistingPreparedClipForTransfer'](arg1);
}

export function GetTransferCapabilities() {
  return window['go']['main']['TransferService']['GetTransferCapabilities']();
}

export function PrepareClipForTransfer(arg1) {
  return window['go']['main']['TransferService']['PrepareClipForTransfer'](arg1);
}

export function StartNativeDragOut(arg1) {
  return window['go']['main']['TransferService']['StartNativeDragOut'](arg1);
}
