// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetExistingPreparedClipForTransfer(arg1:main.PrepareTransferRequest):Promise<main.PreparedTransferItem>;

export function GetTransferCapabilities():Promise<main.TransferCapabilities>;

export function PrepareClipForTransfer(arg1:main.PrepareTransferRequest):Promise<main.PreparedTransferItem>;

export function StartNativeDragOut(arg1:main.StartNativeDragRequest):Promise<boolean>;
