// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GetExistingPreparedClipForTransfer(arg1:app.PrepareTransferRequest):Promise<app.PreparedTransferItem>;

export function GetTransferCapabilities():Promise<app.TransferCapabilities>;

export function PrepareClipForTransfer(arg1:app.PrepareTransferRequest):Promise<app.PreparedTransferItem>;

export function StartNativeDragOut(arg1:app.StartNativeDragRequest):Promise<boolean>;
